@ stdcall SfcInitProt(long long long long long long long)
@ stdcall SfcTerminateWatcherThread()
@ stdcall -stub SfcConnectToServer(long)
@ stdcall -stub SfcClose()
@ stdcall SfcFileException(long ptr long)
@ stdcall -stub SfcInitiateScan()
@ stdcall -stub SfcInstallProtectedFiles()
@ stdcall SfcGetNextProtectedFile(long ptr)
@ stdcall SfcIsFileProtected(ptr wstr)
@ stdcall SfcIsKeyProtected(long wstr long)
@ stdcall SfcWLEventLogoff(ptr)
@ stdcall SfcWLEventLogon(ptr)
